const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=path.join(__dirname,'..','artifacts','browser');
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:8080/';
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();const errors=[],badResponses=[],mediaRequests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)badResponses.push([r.status(),r.url()]);});page.on('request',r=>{if(r.url().endsWith('.mp4'))mediaRequests.push(r.url());});
 const count=async n=>{await page.waitForFunction(n=>document.querySelectorAll('.task-card').length===n,n);assert.equal(await page.locator('.task-card').count(),n);};
 const ready=async()=>{await page.waitForFunction(()=>document.querySelector('#episode-video').readyState>=2);assert.equal(await page.locator('#video-error').isVisible(),false);};
 await page.goto(base,{waitUntil:'networkidle'});await count(40);assert.equal(mediaRequests.length,0,'Video data must not preload in collection');
 await page.locator('.benchmark-tabs [data-benchmark="robotwin"]').click();await count(50);
 await page.goBack();await count(40);
 await page.locator('[data-suite="libero_goal"]').click();await count(10);
 await page.selectOption('#outcome-filter','failures');await count(4);
 await page.fill('#task-search','drawer');await count(2);
 await page.fill('#task-search','no-such-task-xyz');await count(0);assert.equal(await page.locator('#empty-state').isVisible(),true);
 await page.locator('#clear-filters').click();await count(40);
 await page.selectOption('#outcome-filter','perfect');await count(26);
 await page.selectOption('#outcome-filter','all');await page.selectOption('#sort-order','hardest');assert.match(await page.locator('.task-rate').first().textContent(),/0 \/ 10/);
 await page.selectOption('#sort-order','default');
 await page.locator('.media-thumb[data-task="libero_spatial_t00"]').click();await ready();
 assert.equal(await page.locator('.episode-button').count(),10);assert.equal(await page.locator('#episode-status').textContent(),'Success');
 await page.locator('#episode-video').evaluate(async v=>{v.muted=true;await v.play();});await page.waitForFunction(()=>document.querySelector('#episode-video').currentTime>.15);await page.locator('#episode-video').evaluate(v=>v.pause());
 await page.selectOption('#playback-speed','2');assert.equal(await page.locator('#episode-video').evaluate(v=>v.playbackRate),2);
 await page.locator('#next-episode').click();await ready();assert.match(page.url(),/libero_spatial_t00_r01/);
 await page.locator('.episode-button').last().click();await ready();assert.match(page.url(),/libero_spatial_t00_r09/);assert.equal(await page.locator('#next-episode').isDisabled(),true);
 assert.equal(await page.evaluate(()=>document.activeElement.dataset.selectEpisode),'libero_spatial_t00_r09');
 await page.locator('#copy-link').click();await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.length>0);assert.match(await page.locator('#copy-status').textContent(),/copied|http/);
 const shared=page.url();await page.screenshot({path:path.join(output,'player-desktop.png')});
 await page.locator('#close-dialog').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
 await page.locator('.media-thumb[data-task="libero_spatial_t00"]').click();await ready();assert.match(await page.locator('#episode-video').getAttribute('src'),/r00.mp4/);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog').open);
 const deep=await context.newPage();await deep.goto(shared);await deep.waitForFunction(()=>document.querySelector('#episode-video').readyState>=2);assert.match(await deep.locator('#episode-number').textContent(),/10 \/ 10/);await deep.locator('#close-dialog').click();await deep.waitForFunction(()=>!document.querySelector('dialog').open);await deep.close();
 await page.locator('.benchmark-tabs [data-benchmark="robotwin"]').click();await count(50);
 await page.selectOption('#outcome-filter','failures');await count(14);
 await page.fill('#task-search','open laptop');await count(1);
 await page.locator('.media-thumb').click();await ready();assert.equal(await page.locator('.episode-button').count(),1);assert.equal(await page.locator('#episode-status').textContent(),'Timeout');assert.equal(await page.locator('#previous-episode').isDisabled(),true);assert.equal(await page.locator('#next-episode').isDisabled(),true);
 assert.match(await page.locator('#video-note').textContent(),/not simulation time/);
 assert.equal(await page.locator('#episode-video').evaluate(v=>v.videoWidth),1536);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'player-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog').open);await page.selectOption('#outcome-filter','all');await page.fill('#task-search','');await count(50);
 await page.locator('#collection').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'collection-mobile.png')});
 for(const width of [360,768,1024,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Horizontal overflow at ${width}`);}
 assert.deepEqual(errors,[]);assert.deepEqual(badResponses,[]);
 console.log(JSON.stringify({passed:true,desktopAndMobile:true,filters:true,allEpisodeSelection:true,playback:true,deepLinks:true,backCloseReopen:true,timeoutVisible:true,zeroEagerVideos:true,errors,badResponses,mediaRequests:mediaRequests.length},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
